# -*- coding: utf-8 -*-
"""violence_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBFtnWAl9smEwjItk59woghXhxYBSWFW
"""

!wget -O violence_train.zip https://app.roboflow.com/ds/Fa4VJ6GYHU?key=1uaF3xbDKQ

pwd

cd /content/drive/MyDrive/Colab Notebooks

pwd

import zipfile

with zipfile.ZipFile('/content/drive/MyDrive/Colab Notebooks/violence_train.zip') as target_file:
  target_file.extractall('/content/violence_train/')

!cat /content/violence_train/data.yaml

!pip install PyYAML

import yaml

data = {'train' : '/content/violence_train/train/images',
               'val' : '/content/violence_train/valid/images',
               'names' : ['v1'],
               'nc' : 1 }

with open('/content/violence_train/data.yaml','w') as f:
  yaml.dump(data,f)

with open('/content/violence_train/data.yaml', 'r') as f:
  violence_train = yaml.safe_load(f)
  display(violence_train)

!pip install ultralytics

import ultralytics
ultralytics.checks()

# Commented out IPython magic to ensure Python compatibility.
from ultralytics import YOLO
model = YOLO('yolov8s.pt')
# %pwd

print(model.names)

model.train(data='/content/violence_train/data.yaml', epochs=10, batch=32, imgsz=640, patience=5)

print(type(model.names), len(model.names))

print(model.names)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/runs/detect/train4/weights

pwd

!yolo predict model=best.pt source=0 show=True

